title: David Bindel
email: bindel@cornell.edu
description: Academic home page for David Bindel
baseurl: "/~bindel/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]
keep_files: ["present"]
gems: ["jekyll/scholar", "csl/styles"]

defaults:
  -
    scope:
      path: "blurbs"
    values:
      layout: "blurb"

collections:
  blurbs:
    output: true

markdown: kramdown

scholar:
  style: assets/bibliography/ieee-with-url.csl
  bibliography_template: bib
  bibliography_list_tag: ul
