title: David Bindel
email: bindel@cornell.edu
description: Academic home page for David Bindel
baseurl: "/~bindel/"
url: "http://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]
keep_files: ["present"]

defaults:
  -
    scope:
      path: "blurbs"
    values:
      layout: "blurb"
      
collections:
  blurbs:
    output: true
    
markdown: kramdown
