title: David Bindel
email: bindel@cornell.edu
description: Academic home page for David Bindel
baseurl: "/~bindel/"
url: "https://www.cs.cornell.edu/"

encoding: utf-8
timezone: America/New_York

exclude: ["Rakefile"]
keep_files: ["present"]
plugins: ["jekyll/tidy", "jekyll/scholar", "csl/styles"]

defaults:
  -
    scope:
      type: "blurbs"
    values:
      layout: blurb
  -
    scope:
      type: "sermons"
    values:
      layout: sermon

collections:
  blurbs:
    output: true
  sermons:
    output: true

markdown: kramdown

scholar:
  style: assets/bibliography/ieee-with-url.csl
  bibliography_template: bib
  bibliography_item_attributes:
    class: "filtering"
