-
  when: 2022
  role: Committee member
  what: Organizing Committee, SIAM Mathematics of Data Science 2022
  type: [external]
-
  when: 2022
  role: Senior PC member
  what: ACM KDD
  type: [external]
-
  when: 2022
  role: Reviewer
  what: ICML 2022
  type: [external]
-
  when: 2022
  role: Reviewer
  what: AISTATS 2022
  type: [external]
-
  when: 2021
  role: Committee member
  what: COE Research Excellence Awards Committee
  type: [cornell, local]
-
  when: 2021
  role: Committee member
  what: Grad Student Advisor Feedback Task Force
  type: [cornell, local]
-
  when: 2021
  what: CIDA RIF reviewer
  role: Reviewer
  type: [cornell, local]
-
  when: 2021
  role: Committee member
  what: Part-Time Bachelor's Degree Committee
  type: [cornell, local]
-
  when: 2021
  until: 2023
  what: SIAM Journal of Scientific Computing
  role: Associate editor
  type: [external]
-
  when: 2021
  role: Reviewer
  what: ICLR 2022
  type: [external]
-
  when: 2021
  role: Reviewer
  what: ICML 2021
  type: [external]
-
  when: 2021
  role: PC member
  what: UAI 2021
  type: [external]
-
  when: 2021
  until: 2023
  role: Associate Dean for DEI
  what: College of Computing and Information Science
  type: [cornell, local]
-
  when: 2021
  role: Senior PC member
  what: ACM KDD
  type: [external]
-
  when: 2020
  until: 2025
  role: Director
  what: Center for Applied Mathematics
  type: [cornell, cam, local]
-
  when: 2020
  what: ICLR 2020 reviewer
  role: Reviewer
  type: [external]
-
  when: 2020
  what: NeurIPS 2020 reviewer
  role: Reviewer
  type: [external]
-
  when: 2020
  what: ICML 2020 reviewer
  role: Reviewer
  type: [external]
-
  when: 2020
  what: CIDA Website Dev Committee
  role: Committee member
  type: [cornell, local]
-
  when: 2020
  what: CIDA RIF reviewer
  role: Reviewer
  type: [cornell, local]
-
  when: 2019
  until: 2021
  what: Cornell English Language Support Office Advisory Board
  role: Committee member
  type: [cornell, local]
-
  when: 2019
  until: 2020
  what: CIS Dean Search Committee
  role: Committee member
  type: [cornell, local]
-
  when: 2019
  until: 2020
  what: Applied Math Graduate Admissions Committee
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2019
  until: present
  what: Applied Math Membership Committee
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2019
  until: 2020
  what: CS Graduate Admissions Committee
  role: Committee chair
  type: [cornell, cs, local]
-
  when: 2019
  until: 2020
  what: CS Graduate Distinction Committee
-
  when: 2019
  until: present
  what: CS Diversity, Inclusion, and Climate Committee
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2019
  what: Program committee for SIAM CSC
  role: Committee member
  type: [external]
-
  when: 2019
  what: NeurIPS 2019 reviewer
  role: Reviewer
  type: [external]
-
  when: 2019
  what: ICML 2019 reviewer
  role: Reviewer
  type: [external]
-
  when: 2018
  what: 2nd Black in AI Workshop
  role: Program committee member
  type: [external]
-
  when: 2017
  until: 2018
  what: ECE/CAM Faculty Recruiting Committee
  role: External committee member
  type: [cornell, cam, local]
-
  when: 2017
  until: 2018
  what: CS Chair Search Committee
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2017
  until: 2018
  what: CS Graduate Admissions Committee
  role: Committee chair
  type: [cornell, cs, local]
-
  when: 2018
  what: SIAM Applied Linear Algebra Conference
  url: http://www.math.hkbu.edu.hk/siam-ala18/
  role: Scientific committee co-chair
  type: [external]
-
  when: 2017
  what: IEEE International Parallel and Distributed Processing Symposium
  role: Program committee member
  type: [external]
-
  when: 2017
  until: 2017
  what: CS Colloquium Committee
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2017
  until: 2017
  what: Applied Math Graduate Admissions Committee
  role: Committee Member
  type: [cornell, cam, local]
-
  when: 2016
  until: 2017
  what: CS Faculty Recruiting Committee
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2016
  what: SIAM Annual Meeting
  url: http://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=23486
  role: Minisymposium organizer
  type: [external]
-
  when: 2016
  what: IEEE International Parallel and Distributed Processing Symposium
  url: http://www.ipdps.org/ipdps2016/2016_program_committee.html
  role: Program committee member
  type: [external]
-
  when: 2015
  until: 2016
  what: CS Graduate Admissions
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2015
  what: Applied Math Curriculum Review Committee
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2015
  what: IEEE International Parallel and Distributed Processing Symposium
  url: http://www.ipdps.org/ipdps2015/2015_program_committee.html
  role: Program committee member
  type: [external]
-
  when: 2015
  what: Workshop on Development of Modern Methods for Linear Algebra
  url: http://www.dbindel.net/dmml
  role: Organizing committee member
  type: [external]
-
  when: 2015
  until: present
  what: Householder Symposium on Numerical Linear Algebra
  url: http://www.math.vt.edu/HHXX/
  role: Scientific committee member
  type: [external]
-
  when: 2014
  what: BigRed Hacks
  url: https://www.bigredhacks.com/
  role: Judge
  type: [cornell, local]
-
  when: 2013
  until: 2014
  what: Applied Math Graduate Admissions
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2014
  what: Supercomputing
  url: http://sc14.supercomputing.org/
  role: Poster commitee member
  type: [external]
-
  when: 2013
  what: Fourth New York Conference on Applied Mathematics
  url: https://www.math.cornell.edu/~scan/NYCAM/
  role: Local organizer
  type: [external]
-
  when: 2013
  what: Supercomputing
  url: http://sc13.supercomputing.org/content/committees.html
  role: Technical program committee member
  type: [external]
-
  when: 2012
  until: 2015
  what: SIAM Activity Group on Linear Algebra
  url: http://siags.siam.org/siagla
  role: Secretary
  type: [external]
-
  when: 2012
  what: Third New York Conference on Applied Mathematics
  url: http://homepages.rpi.edu/~lif/NYCAM/index.html
  role: Organizing committee member
  type: [external]
-
  when: 2011
  until: 2012
  what: Applied Math Graduate Admissions
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2011
  what: Second New York Conference on Applied Mathematics
  url: http://gibbs.math.buffalo.edu/nycam/
  role: Organizing committee member
  type: [external]
-
  when: 2011
  until: 2014
  what: Cornell Faculty Advisory Board on Information Technology
  url: http://theuniversityfaculty.cornell.edu/faculty-senate/faculty-advisory-board-on-information-technologies-fabit/
  role: Committee member
  type: [cornell, local]
-
  when: 2010
  until: 2011
  what: CS Graduate Admissions
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2010
  until: 2011
  what: Applied Math Graduate Admissions
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2017
  until: 2020
  what: Journal of Computational Mathematics
  url: http://www.global-sci.org/jcm/
  role: Associate editor
  type: [external]
-
  when: 2010
  until: present
  what: Numerical Linear Algebra with Applications
  url: http://onlinelibrary.wiley.com/journal/10.1002/%28ISSN%291099-1506
  role: Editor
  type: [external]
-
  when: 2009
  until: 2010
  what: CS Graduate Admissions
  role: Committee member
  type: [cornell, cs, local]
-
  when: 2009
  until: 2010
  what: Applied Math Graduate Admissions
  role: Committee member
  type: [cornell, cam, local]
-
  when: 2008
  until: present
  what: Electronic Transactions on Numerical Analysis
  url: http://etna.mcs.kent.edu/
  role: Managing editor
  type: [external]
-
  when: 2009
  until: present
  what: Cornell Scientific Computing and Numeric Seminar
  url: http://www.cse.cornell.edu/scan/
  role: Organizer
  type: [cornell, local]
-
  when: 2007
  until: 2009
  what: NYU Numerical Analysis / Scientific Computing Seminar
  role: Organizer
  type: [nyu, local]
-
  when: 2007
  what: SIAM Computational Science and Engineering Meeting
  url: http://meetings.siam.org/sess/dsp_programsess.cfm?SESSIONCODE=6042
  role: Minisymposium organizer
  type: [external]
-
  when: 2002
  until: 2004
  what: IEEE 754R Standard Revision Committee
  url: http://grouper.ieee.org/groups/754/
  role: Secretary
  type: [external]
